Repository cvanaret/Uno, pull requests merged in 2025-08, with the labels that each got.

#247 Prep for v2.0.1
  CITATION.cff
  CMakeLists.txt
  uno/Uno.cpp
Labels: release

#250 Report the direction as INFEASIBLE if the augmented matrix is singular
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.cpp
  uno/ingredients/subproblem_solvers/MA57/MA57Solver.cpp
  uno/ingredients/subproblem_solvers/MUMPS/MUMPSSolver.cpp
Labels: improvement

#251 [WIP] Unit tests in CI on Windows
  .github/workflows/build-macos.yml
  .github/workflows/build-msvc.yml
  .github/workflows/unit-tests-linux.yml
  .github/workflows/unit-tests-msvc.yml
  CMakeLists.txt
  unotest/unotest.cpp
Labels: CI, improvement

#253 Got rid of feasibility multipliers, maintain a second set in FeasibilityRestoration
  bindings/AMPL/uno_ampl.cpp
  uno/ingredients/constraint_relaxation_strategies/FeasibilityRestoration.cpp
  uno/ingredients/constraint_relaxation_strategies/FeasibilityRestoration.hpp
  uno/ingredients/constraint_relaxation_strategies/UnconstrainedStrategy.cpp
  uno/ingredients/constraint_relaxation_strategies/UnconstrainedStrategy.hpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/globalization_mechanisms/GlobalizationMechanism.cpp
  uno/ingredients/globalization_mechanisms/TrustRegionStrategy.cpp
  uno/ingredients/inequality_handling_methods/InequalityHandlingMethod.hpp
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/InequalityConstrainedMethod.cpp
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/InequalityConstrainedMethod.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/BarrierParameterUpdateStrategy.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/BarrierParameterUpdateStrategy.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointMethod.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointMethod.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.hpp
  uno/ingredients/subproblem/Subproblem.cpp
  uno/ingredients/subproblem/Subproblem.hpp
  uno/optimization/Direction.cpp
  uno/optimization/Direction.hpp
  uno/optimization/Iterate.cpp
  uno/optimization/Iterate.hpp
  uno/optimization/OptimizationProblem.cpp
  uno/optimization/OptimizationProblem.hpp
  uno/optimization/Result.cpp
Labels: improvement

#255 Determine the presence of curvature in the subproblem
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.hpp
  uno/ingredients/hessian_models/ExactHessian.cpp
  uno/ingredients/hessian_models/ExactHessian.hpp
  uno/ingredients/hessian_models/HessianModel.hpp
  uno/ingredients/hessian_models/IdentityHessian.cpp
  uno/ingredients/hessian_models/IdentityHessian.hpp
  uno/ingredients/hessian_models/ZeroHessian.cpp
  uno/ingredients/hessian_models/ZeroHessian.hpp
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/InequalityConstrainedMethod.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.hpp
  uno/ingredients/subproblem/Subproblem.cpp
  uno/ingredients/subproblem/Subproblem.hpp
  uno/optimization/OptimizationProblem.cpp
  uno/optimization/OptimizationProblem.hpp
Labels: improvement

#258 Split primal and dual tolerances
  uno/ingredients/constraint_relaxation_strategies/ConstraintRelaxationStrategy.cpp
  uno/ingredients/constraint_relaxation_strategies/ConstraintRelaxationStrategy.hpp
  uno/ingredients/constraint_relaxation_strategies/FeasibilityRestoration.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.hpp
  uno/ingredients/globalization_mechanisms/TrustRegionStrategy.cpp
  uno/ingredients/globalization_mechanisms/TrustRegionStrategy.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/BarrierParameterUpdateStrategy.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/BarrierParameterUpdateStrategy.hpp
  uno/model/BoundRelaxedModel.cpp
  uno/optimization/OptimizationProblem.cpp
  uno/optimization/OptimizationProblem.hpp
  uno/options/DefaultOptions.cpp
  uno/options/Presets.cpp
Labels: improvement

#259 Do not overwrite debug flags for gcc
  CMakeLists.txt
Labels: improvement

#257 Test the filterslp preset with BQPD as the LP solver
  .github/julia/runtests_uno_filterslp_bqpd.jl
  .github/workflows/julia-tests-ubuntu.yml
Labels: CI

#261 Interface to HiGHS as a QP solver
  .github/julia/runtests_uno_filtersqp_highs.jl
  .github/workflows/julia-tests-ubuntu.yml
  bindings/AMPL/AMPLModel.cpp
  bindings/AMPL/AMPLModel.hpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.hpp
  uno/ingredients/hessian_models/ExactHessian.cpp
  uno/ingredients/hessian_models/ExactHessian.hpp
  uno/ingredients/hessian_models/HessianModel.hpp
  uno/ingredients/hessian_models/IdentityHessian.cpp
  uno/ingredients/hessian_models/IdentityHessian.hpp
  uno/ingredients/hessian_models/ZeroHessian.cpp
  uno/ingredients/hessian_models/ZeroHessian.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.hpp
  uno/ingredients/regularization_strategies/NoRegularization.hpp
  uno/ingredients/regularization_strategies/PrimalDualRegularization.hpp
  uno/ingredients/regularization_strategies/PrimalRegularization.hpp
  uno/ingredients/regularization_strategies/RegularizationStrategy.hpp
  uno/ingredients/subproblem/Subproblem.cpp
  uno/ingredients/subproblem/Subproblem.hpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDSolver.cpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDSolver.hpp
  uno/ingredients/subproblem_solvers/DirectSymmetricIndefiniteLinearSolver.hpp
  uno/ingredients/subproblem_solvers/HiGHS/HiGHSSolver.cpp
  uno/ingredients/subproblem_solvers/HiGHS/HiGHSSolver.hpp
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.cpp
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.hpp
  uno/ingredients/subproblem_solvers/MA57/MA57Solver.cpp
  uno/ingredients/subproblem_solvers/MA57/MA57Solver.hpp
  uno/ingredients/subproblem_solvers/MUMPS/MUMPSSolver.cpp
  uno/ingredients/subproblem_solvers/MUMPS/MUMPSSolver.hpp
  uno/ingredients/subproblem_solvers/QPSolverFactory.cpp
  uno/ingredients/subproblem_solvers/QPSolverFactory.hpp
  uno/model/BoundRelaxedModel.hpp
  uno/model/FixedBoundsConstraintsModel.cpp
  uno/model/FixedBoundsConstraintsModel.hpp
  uno/model/HomogeneousEqualityConstrainedModel.cpp
  uno/model/HomogeneousEqualityConstrainedModel.hpp
  uno/model/Model.hpp
  uno/optimization/OptimizationProblem.cpp
  uno/optimization/OptimizationProblem.hpp
Labels: feature

#263 [CI] Test the filtersqp preset + identity Hessian model
  .github/julia/runtests_uno_filtersqp_bqpd_identity.jl
  .github/workflows/build-macos.yml
  .github/workflows/julia-tests-ubuntu.yml
Labels: CI

#270 Store NNZ of symmetric matrix in linear solvers
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.cpp
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.hpp
  uno/ingredients/subproblem_solvers/MA57/MA57Solver.cpp
  uno/ingredients/subproblem_solvers/MA57/MA57Solver.hpp
  uno/ingredients/subproblem_solvers/MUMPS/MUMPSSolver.cpp
  uno/ingredients/subproblem_solvers/MUMPS/MUMPSSolver.hpp
Labels: improvement

#276 Subproblem: compute sparsity of *lower triangular* part of symmetric augmented matrix
  uno/ingredients/subproblem/Subproblem.cpp
Labels: improvement

#277 Use int* instead of size_t* to store sparsity
  bindings/AMPL/AMPLModel.cpp
  bindings/AMPL/AMPLModel.hpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.hpp
  uno/ingredients/hessian_models/ExactHessian.cpp
  uno/ingredients/hessian_models/ExactHessian.hpp
  uno/ingredients/hessian_models/HessianModel.hpp
  uno/ingredients/hessian_models/IdentityHessian.cpp
  uno/ingredients/hessian_models/IdentityHessian.hpp
  uno/ingredients/hessian_models/ZeroHessian.cpp
  uno/ingredients/hessian_models/ZeroHessian.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.hpp
  uno/ingredients/subproblem/Subproblem.cpp
  uno/ingredients/subproblem/Subproblem.hpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDEvaluationSpace.cpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDEvaluationSpace.hpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDSolver.cpp
  uno/ingredients/subproblem_solvers/COOEvaluationSpace.cpp
  uno/ingredients/subproblem_solvers/COOEvaluationSpace.hpp
  uno/ingredients/subproblem_solvers/HiGHS/HiGHSEvaluationSpace.cpp
  uno/ingredients/subproblem_solvers/HiGHS/HiGHSEvaluationSpace.hpp
  uno/linear_algebra/Indexing.hpp
  uno/model/BoundRelaxedModel.hpp
  uno/model/FixedBoundsConstraintsModel.cpp
  uno/model/FixedBoundsConstraintsModel.hpp
  uno/model/HomogeneousEqualityConstrainedModel.cpp
  uno/model/HomogeneousEqualityConstrainedModel.hpp
  uno/model/Model.hpp
  uno/optimization/OptimizationProblem.cpp
  uno/optimization/OptimizationProblem.hpp
Labels: improvement

#280 Fixed includes, ++ operator, minor changes
  uno/Uno.cpp
  uno/ingredients/constraint_relaxation_strategies/ConstraintRelaxationStrategy.hpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.hpp
  uno/ingredients/globalization_mechanisms/BacktrackingLineSearch.cpp
  uno/ingredients/globalization_mechanisms/BacktrackingLineSearch.hpp
  uno/ingredients/globalization_mechanisms/TrustRegionStrategy.cpp
  uno/ingredients/globalization_mechanisms/TrustRegionStrategy.hpp
  uno/ingredients/globalization_strategies/GlobalizationStrategy.cpp
  uno/ingredients/globalization_strategies/GlobalizationStrategy.hpp
  uno/ingredients/globalization_strategies/GlobalizationStrategyFactory.cpp
  uno/ingredients/globalization_strategies/GlobalizationStrategyFactory.hpp
  uno/ingredients/globalization_strategies/ProgressMeasures.hpp
  uno/ingredients/globalization_strategies/l1MeritFunction.cpp
  uno/ingredients/globalization_strategies/l1MeritFunction.hpp
  uno/ingredients/globalization_strategies/switching_methods/filter_methods/filters/Filter.cpp
  uno/ingredients/globalization_strategies/switching_methods/filter_methods/filters/NonmonotoneFilter.cpp
  uno/ingredients/hessian_models/ExactHessian.cpp
  uno/ingredients/hessian_models/ExactHessian.hpp
  uno/ingredients/hessian_models/IdentityHessian.cpp
  uno/ingredients/hessian_models/ZeroHessian.cpp
  uno/ingredients/inequality_handling_methods/InequalityHandlingMethod.hpp
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/InequalityConstrainedMethod.cpp
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/InequalityConstrainedMethod.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointMethod.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.cpp
  uno/ingredients/regularization_strategies/PrimalDualRegularization.hpp
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.cpp
  uno/ingredients/subproblem_solvers/MA57/MA57Solver.cpp
  uno/linear_algebra/COOFormat.hpp
  uno/linear_algebra/COOMatrix.hpp
  uno/linear_algebra/CSCFormat.hpp
  uno/linear_algebra/SparseStorage.hpp
  uno/linear_algebra/SparseVector.hpp
  uno/linear_algebra/Vector.hpp
  uno/model/FixedBoundsConstraintsModel.cpp
  uno/model/FixedBoundsConstraintsModel.hpp
  uno/model/HomogeneousEqualityConstrainedModel.cpp
  uno/model/HomogeneousEqualityConstrainedModel.hpp
  uno/optimization/Iterate.cpp
  uno/options/Options.cpp
  uno/symbolic/CollectionAdapter.hpp
  uno/symbolic/Concatenation.hpp
  uno/symbolic/Range.hpp
  uno/symbolic/VectorExpression.hpp
  uno/symbolic/VectorView.hpp
Labels: improvement

#283 Prep for v2.0.2
  CITATION.cff
  CMakeLists.txt
  README.md
  docs/developers/checklists.md
  docs/figures/uno_performance_profile.png
  uno/Uno.cpp
Labels: release

#287 Refactoring: improve handling of default options
  bindings/AMPL/uno_ampl.cpp
  uno/options/DefaultOptions.cpp
  uno/options/DefaultOptions.hpp
  uno/options/Options.cpp
  uno/options/Options.hpp
Labels: improvement
