Repository cvanaret/Uno, pull requests merged in 2025-07, with the labels that each got.

#196 Prep for v2.0.0
  CITATION.cff
  CMakeLists.txt
  README.md
  uno/Uno.cpp
Labels: release

#199 Fix the cross-compilation with BQPD
  .github/julia/build_tarballs_release.jl
  .github/julia/build_tarballs_yggdrasil.jl
Labels: CI

#202 Fixed missing include in Vector (for Apple Darwin)
  uno/linear_algebra/Vector.hpp
Labels: bug

#203 Fixed missing include (Apple Darwin)
  uno/optimization/Multipliers.cpp
Labels: bug

#211 Added missing include in BarrierParameterUpdateStrategy
  uno/ingredients/inequality_handling_methods/interior_point_methods/BarrierParameterUpdateStrategy.cpp
Labels: CI

#213 [WIP] Compiling static and shared libraries of Uno + make install
  .github/julia/build_tarballs_release.jl
  .github/julia/build_tarballs_yggdrasil.jl
  .github/workflows/unit-tests-ubuntu.yml
  CMakeLists.txt
Labels: feature, improvement

#228 Julia CI for filtersqp: included an MOI test that shouldn't fail
  .github/julia/runtests_uno_filtersqp.jl
  bindings/AMPL/AMPLModel.cpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDSolver.cpp
Labels: CI

#235 Proper resize in MA27Solver::do_numerical_factorization()
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.cpp
  uno/ingredients/subproblem_solvers/MA27/MA27Solver.hpp
Labels: bug

#234 Test MA27 and MA57 on ANL cluster Moonshot
  .github/julia/runtests_uno_ipopt_ma27.jl
  .github/julia/runtests_uno_ipopt_ma57.jl
  .github/workflows/julia-tests-hsl.yml
Labels: CI

#236 [CI] Cross-compile Uno in parallel for future releases
  .github/julia/build_tarballs_release.jl
  .github/julia/generate_binaries.jl
  .github/workflows/release.yml
Labels: CI

#237 Lagrangian sign convention in ASL: call the scaling function once instead of flipping the signs
  bindings/AMPL/AMPLModel.cpp
  bindings/AMPL/AMPLModel.hpp
Labels: improvement

#243 [WIP] Compute the residuals wrt the problem (original or feasibility) being currently solved
  uno/Uno.cpp
  uno/Uno.hpp
  uno/ingredients/constraint_relaxation_strategies/ConstraintRelaxationStrategy.cpp
  uno/ingredients/constraint_relaxation_strategies/ConstraintRelaxationStrategy.hpp
  uno/ingredients/constraint_relaxation_strategies/FeasibilityRestoration.cpp
  uno/ingredients/constraint_relaxation_strategies/FeasibilityRestoration.hpp
  uno/ingredients/constraint_relaxation_strategies/UnconstrainedStrategy.cpp
  uno/ingredients/constraint_relaxation_strategies/UnconstrainedStrategy.hpp
  uno/ingredients/constraint_relaxation_strategies/l1Relaxation.cpp
  uno/ingredients/constraint_relaxation_strategies/l1Relaxation.hpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.hpp
  uno/ingredients/globalization_mechanisms/BacktrackingLineSearch.cpp
  uno/ingredients/globalization_mechanisms/BacktrackingLineSearch.hpp
  uno/ingredients/globalization_mechanisms/GlobalizationMechanism.cpp
  uno/ingredients/globalization_mechanisms/GlobalizationMechanism.hpp
  uno/ingredients/globalization_mechanisms/TrustRegionStrategy.cpp
  uno/ingredients/globalization_mechanisms/TrustRegionStrategy.hpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointMethod.cpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDSolver.hpp
  uno/ingredients/subproblem_solvers/HiGHS/HiGHSSolver.cpp
  uno/ingredients/subproblem_solvers/MA57/MA57Solver.hpp
  uno/linear_algebra/SparseSymmetricMatrix.hpp
  uno/linear_algebra/SparseVector.hpp
  uno/optimization/Iterate.cpp
  uno/optimization/Iterate.hpp
  uno/optimization/OptimizationProblem.cpp
  uno/optimization/OptimizationProblem.hpp
  uno/optimization/Result.cpp
Labels: bug, improvement

#245 Removed the byrd preset
  README.md
  uno/ingredients/constraint_relaxation_strategies/ConstraintRelaxationStrategyFactory.cpp
  uno/ingredients/constraint_relaxation_strategies/l1Relaxation.cpp
  uno/ingredients/constraint_relaxation_strategies/l1Relaxation.hpp
  uno/options/DefaultOptions.cpp
  uno/options/Presets.cpp
Labels: improvement
