Repository cvanaret/Uno, pull requests merged in 2025-06, with the labels that each got.

#172 Fix the number of nonzeros in the regularized Hessian/augmented system
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/LPSubproblem.cpp
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/QPSubproblem.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointMethod.cpp
  uno/ingredients/regularization_strategies/NoRegularization.hpp
  uno/ingredients/regularization_strategies/PrimalDualRegularization.hpp
  uno/ingredients/regularization_strategies/PrimalRegularization.hpp
  uno/ingredients/regularization_strategies/RegularizationStrategy.hpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDSolver.cpp
  uno/ingredients/subproblem_solvers/BQPD/BQPDSolver.hpp
  uno/ingredients/subproblem_solvers/HiGHS/HiGHSSolver.cpp
  uno/ingredients/subproblem_solvers/HiGHS/HiGHSSolver.hpp
  uno/ingredients/subproblem_solvers/LPSolver.hpp
  uno/ingredients/subproblem_solvers/QPSolver.hpp
Labels: bug

#180 FeasibilityRestoration: move the switch from phase 1 to phase 2 to the end
  uno/ingredients/constraint_relaxation_strategies/FeasibilityRestoration.cpp
  uno/tools/Statistics.cpp
Labels: bug

#187 Compute the (primal and dual) regularization indices automatically
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.cpp
  uno/ingredients/constraint_relaxation_strategies/l1RelaxedProblem.hpp
  uno/ingredients/inequality_handling_methods/inequality_constrained_methods/InequalityConstrainedMethod.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointMethod.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.cpp
  uno/ingredients/inequality_handling_methods/interior_point_methods/PrimalDualInteriorPointProblem.hpp
  uno/ingredients/regularization_strategies/PrimalRegularization.hpp
  uno/ingredients/subproblem/Subproblem.cpp
  uno/ingredients/subproblem/Subproblem.hpp
  uno/optimization/OptimizationProblem.cpp
  uno/optimization/OptimizationProblem.hpp
Labels: improvement

#190 [CI] Compile Uno with MUMPS
  .github/workflows/build-macos.yml
  .github/workflows/build-msvc.yml
  .github/workflows/build-windows.yml
  .github/workflows/unit-tests-ubuntu.yml
  CMakeLists.txt
Labels: CI

#192 Bugfix: template inference in empty std::array
  uno/Uno.cpp
  uno/ingredients/constraint_relaxation_strategies/ConstraintRelaxationStrategy.hpp
  uno/ingredients/globalization_mechanisms/GlobalizationMechanism.hpp
  uno/ingredients/inequality_handling_methods/InequalityHandlingMethod.hpp
  uno/ingredients/inequality_handling_methods/InequalityHandlingMethodFactory.cpp
  uno/ingredients/subproblem_solvers/LPSolver.hpp
  uno/ingredients/subproblem_solvers/LPSolverFactory.cpp
  uno/ingredients/subproblem_solvers/LPSolverFactory.hpp
  uno/ingredients/subproblem_solvers/QPSolverFactory.cpp
  uno/ingredients/subproblem_solvers/QPSolverFactory.hpp
  uno/optimization/WarmstartInformation.hpp
  uno/options/DefaultOptions.cpp
  uno/options/Presets.cpp
Labels: bug
